language: node_js
node_js: 
  - "stable"
install:
  - npm install
deploy:
  provider: npm
  email: "cenietob@gmail.com"
  api_key: ${NPM_API_KEY}
  skip_cleanup: true
  on:
    branch: master
    tags: true